# Generated by Django 3.0.6 on 2020-05-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllProducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommended',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
