# Generated by Django 3.0.6 on 2020-05-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='CVC',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='Card_number',
            field=models.CharField(max_length=19),
        ),
    ]
